"""
Python version of enums from ipmi_monitoring_bitmasks.h
"""

from enum import Enum

class IpmiMonitoringSensorBitmaskType(Enum):
    """IPMI Monitoring Sensor Bitmask Type"""
    THRESHOLD = 0x00
    TRANSITION_STATE = 0x01
    STATE = 0x02
    PREDICTIVE_FAILURE = 0x03
    LIMIT = 0x04
    PERFORMANCE = 0x05
    TRANSITION_SEVERITY = 0x06
    DEVICE_PRESENT = 0x07
    DEVICE_ENABLED = 0x08
    TRANSITION_AVAILABILITY = 0x09
    REDUNDANCY = 0x0A
    ACPI_POWER_STATE = 0x0B
    PHYSICAL_SECURITY = 0x0C
    PLATFORM_SECURITY_VIOLATION_ATTEMPT = 0x0D
    PROCESSOR = 0x0E
    POWER_SUPPLY = 0x0F
    POWER_UNIT = 0x10
    COOLING_DEVICE = 0x11
    OTHER_UNITS_BASED_SENSOR = 0x12
    MEMORY = 0x13
    DRIVE_SLOT = 0x14
    POST_MEMORY_RESIZE = 0x15
    SYSTEM_FIRMWARE_PROGRESS = 0x16
    EVENT_LOGGING_DISABLED = 0x17
    WATCHDOG1 = 0x18
    SYSTEM_EVENT = 0x19
    CRITICAL_INTERRUPT = 0x1A
    BUTTON_SWITCH = 0x1B
    MODULE_BOARD = 0x1C
    MICROCONTROLLER_COPROCESSOR = 0x1D
    ADD_IN_CARD = 0x1E
    CHASSIS = 0x1F
    CHIP_SET = 0x20
    OTHER_FRU = 0x21
    CABLE_INTERCONNECT = 0x22
    TERMINATOR = 0x23
    SYSTEM_BOOT_INITIATED = 0x24
    BOOT_ERROR = 0x25
    OS_BOOT = 0x26
    OS_CRITICAL_STOP = 0x27
    SLOT_CONNECTOR = 0x28
    SYSTEM_ACPI_POWER_STATE = 0x29
    WATCHDOG2 = 0x2A
    PLATFORM_ALERT = 0x2B
    ENTITY_PRESENCE = 0x2C
    MONITOR_ASIC_IC = 0x2D
    LAN = 0x2E
    MANAGEMENT_SUBSYSTEM_HEALTH = 0x2F
    BATTERY = 0x30
    SESSION_AUDIT = 0x31
    VERSION_CHANGE = 0x32
    FRU_STATE = 0x33
    OEM = 0xFE
    UNKNOWN = 0xFF

class IpmiMonitoringSensorBitmaskThreshold(Enum):
    """IPMI Monitoring Sensor Bitmask Threshold"""
    AT_OR_BELOW_LOWER_NON_CRITICAL_THRESHOLD = 0x0001
    AT_OR_BELOW_LOWER_CRITICAL_THRESHOLD = 0x0002
    AT_OR_BELOW_LOWER_NON_RECOVERABLE_THRESHOLD = 0x0004
    AT_OR_BELOW_UPPER_NON_CRITICAL_THRESHOLD = 0x0008
    AT_OR_BELOW_UPPER_CRITICAL_THRESHOLD = 0x0010
    AT_OR_BELOW_UPPER_NON_RECOVERABLE_THRESHOLD = 0x0020

class IpmiMonitoringSensorBitmaskTransition(Enum):
    """IPMI Monitoring Sensor Bitmask Transition"""
    TO_IDLE = 0x0001
    TO_ACTIVE = 0x0002
    TO_BUSY = 0x0004

class IpmiMonitoringSensorBitmaskState(Enum):
    """IPMI Monitoring Sensor Bitmask State"""
    DEASSERTED = 0x0001
    ASSERTED = 0x0002

class IpmiMonitoringSensorBitmaskPredictiveFailure(Enum):
    """IPMI Monitoring Sensor Bitmask Predictive Failure"""
    DEASSERTED = 0x0001
    ASSERTED = 0x0002

class IpmiMonitoringSensorBitmaskLimit(Enum):
    """IPMI Monitoring Sensor Bitmask Limit"""
    NOT_EXCEEDED = 0x0001
    EXCEEDED = 0x0002

class IpmiMonitoringSensorBitmaskPerformance(Enum):
    """IPMI Monitoring Sensor Bitmask Performance"""
    MET = 0x0001
    LAGS = 0x0002

class IpmiMonitoringSensorBitmaskTransitionSeverity(Enum):
    """IPMI Monitoring Sensor Bitmask Transition Severity"""
    TO_OK = 0x0001
    TO_NON_CRITICAL_FROM_OK = 0x0002
    TO_CRITICAL_FROM_LESS_SEVERE = 0x0004
    TO_NON_RECOVERABLE_FROM_LESS_SEVERE = 0x0008
    TO_NON_CRITICAL_FROM_MORE_SEVERE = 0x0010
    TO_CRITICAL_FROM_NON_RECOVERABLE = 0x0020
    TO_NON_RECOVERABLE = 0x0040
    MONITOR = 0x0080
    INFORMATIONAL = 0x0100

class IpmiMonitoringSensorBitmaskDevicePresent(Enum):
    """IPMI Monitoring Sensor Bitmask Device Present"""
    REMOVED_DEVICE_ABSENT = 0x0001
    INSERTED_DEVICE_PRESENT = 0x0002

class IpmiMonitoringSensorBitmaskDeviceEnabled(Enum):
    """IPMI Monitoring Sensor Bitmask Device Enabled"""
    DISABLED = 0x0001
    ENABLED = 0x0002

class IpmiMonitoringSensorBitmaskTransitionAvailability(Enum):
    """IPMI Monitoring Sensor Bitmask Transition Availability"""
    TO_RUNNING = 0x0001
    TO_IN_TEST = 0x0002
    TO_POWER_OFF = 0x0004
    TO_ON_LINE = 0x0008
    TO_OFF_LINE = 0x0010
    TO_OFF_DUTY = 0x0020
    TO_DEGRADED = 0x0040
    TO_POWER_SAVE = 0x0080
    INSTALL_ERROR = 0x0100

class IpmiMonitoringSensorBitmaskRedundancy(Enum):
    """IPMI Monitoring Sensor Bitmask Redundancy"""
    FULLY_REDUNDANT = 0x0001
    REDUNDANCY_LOST = 0x0002
    REDUNDANCY_DEGRADED = 0x0004
    NON_REDUNDANT_SUFFICIENT_RESOURCES_FROM_REDUNDANT = 0x0008
    NON_REDUNDANT_SUFFICIENT_RESOURCES_FROM_INSUFFICIENT_RESOURCES = 0x0010
    NON_REDUNDANT_INSUFFICIENT_RESOURCES = 0x0020
    REDUNDANCY_DEGRADED_FROM_FULLY_REDUNDANT = 0x0040
    REDUNDANCY_DEGRADED_FROM_NON_REDUNDANT = 0x0080

class IpmiMonitoringSensorBitmaskAcpiPowerState(Enum):
    """IPMI Monitoring Sensor Bitmask ACPI Power State"""
    D0_POWER_STATE = 0x0001
    D1_POWER_STATE = 0x0002
    D2_POWER_STATE = 0x0004
    D3_POWER_STATE = 0x0008

class IpmiMonitoringSensorBitmaskPhysicalSecurity(Enum):
    """IPMI Monitoring Sensor Bitmask Physical Security"""
    GENERAL_CHASSIS_INTRUSION = 0x0001
    DRIVE_BAY_INTRUSION = 0x0002
    IO_CARD_INTRUSION = 0x0004
    PROCESSOR_AREA_INTRUSION = 0x0008
    LAN_LEASH_LOST = 0x0010
    UNAUTHORIZED_DOCK_UNDOCK = 0x0020
    FAN_AREA_INTRUSION = 0x0040

class IpmiMonitoringSensorBitmaskPlatformSecurityViolationAttempt(Enum):
    """IPMI Monitoring Sensor Bitmask Platform Security Violation Attempt"""
    SECURE_MODE_VIOLATION_ATTEMPT = 0x0001
    PRE_BOOT_PASSWORD_VIOLATION_USER_PASSWORD = 0x0002
    PRE_BOOT_PASSWORD_VIOLATION_ATTEMPT_SETUP_PASSWORD = 0x0004
    PRE_BOOT_PASSWORD_VIOLATION_NETWORK_BOOT_PASSWORD = 0x0008
    OTHER_PRE_BOOT_PASSWORD_VIOLATION = 0x0010
    OUT_OF_BAND_ACCESS_PASSWORD_VIOLATION = 0x0020

class IpmiMonitoringSensorBitmaskProcessor(Enum):
    """IPMI Monitoring Sensor Bitmask Processor"""
    IERR = 0x0001
    THERMAL_TRIP = 0x0002
    FRB1_BIST_FAILURE = 0x0004
    FRB2_HANG_IN_POST_FAILURE = 0x0008
    FRB3_PROCESSOR_STARTUP_INITIALIZATION_FAILURE = 0x0010
    CONFIGURATION_ERROR = 0x0020
    SMBIOS_UNCORRECTABLE_CPU_COMPLEX_ERROR = 0x0040
    PROCESSOR_PRESENCE_DETECTED = 0x0080
    PROCESSOR_DISABLED = 0x0100
    TERMINATOR_PRESENCE_DETECTED = 0x0200
    PROCESSOR_AUTOMATICALLY_THROTTLED = 0x0400
    MACHINE_CHECK_EXCEPTION = 0x0800
    CORRECTABLE_MACHINE_CHECK_ERROR = 0x1000

class IpmiMonitoringSensorBitmaskPowerSupply(Enum):
    """IPMI Monitoring Sensor Bitmask Power Supply"""
    PRESENCE_DETECTED = 0x0001
    POWER_SUPPLY_FAILURE_DETECTED = 0x0002
    PREDICTIVE_FAILURE = 0x0004
    POWER_SUPPLY_INPUT_LOST_AC_DC = 0x0008
    POWER_SUPPLY_INPUT_LOST_OR_OUT_OF_RANGE = 0x0010
    POWER_SUPPLY_INPUT_OUT_OF_RANGE_BUT_PRESENT = 0x0020
    CONFIGURATION_ERROR = 0x0040
    POWER_SUPPLY_INACTIVE = 0x0080

class IpmiMonitoringSensorBitmaskPowerUnit(Enum):
    """IPMI Monitoring Sensor Bitmask Power Unit"""
    POWER_OFF_POWER_DOWN = 0x0001
    POWER_CYCLE = 0x0002
    _240VA_POWER_DOWN = 0x0004
    INTERLOCK_POWER_DOWN = 0x0008
    AC_LOST = 0x0010
    SOFT_POWER_CONTROL_FAILURE = 0x0020
    POWER_UNIT_FAILURE_DETECTED = 0x0040
    PREDICTIVE_FAILURE = 0x0080

class IpmiMonitoringSensorBitmaskMemory(Enum):
    """IPMI Monitoring Sensor Bitmask Memory"""
    CORRECTABLE_MEMORY_ERROR = 0x0001
    UNCORRECTABLE_MEMORY_ERROR = 0x0002
    PARITY = 0x0004
    MEMORY_SCRUB_FAILED = 0x0008
    MEMORY_DEVICE_DISABLED = 0x0010
    CORRECTABLE_MEMORY_ERROR_LOGGING_LIMIT_REACHED = 0x0020
    PRESENCE_DETECTED = 0x0040
    CONFIGURATION_ERROR = 0x0080
    SPARE = 0x0100
    MEMORY_AUTOMATICALLY_THROTTLED = 0x0200
    CRITICAL_OVERTEMPERATURE = 0x0400

class IpmiMonitoringSensorBitmaskDriveSlot(Enum):
    """IPMI Monitoring Sensor Bitmask Drive Slot"""
    DRIVE_PRESENCE = 0x0001
    DRIVE_FAULT = 0x0002
    PREDICTIVE_FAILURE = 0x0004
    HOT_SPARE = 0x0008
    CONSISTENCY_CHECK_PARITY_CHECK_IN_PROGRESS = 0x0010
    IN_CRITICAL_ARRAY = 0x0020
    IN_FAILED_ARRAY = 0x0040
    REBUILD_REMAP_IN_PROGRESS = 0x0080
    REBUILD_REMAP_ABORTED = 0x0100

class IpmiMonitoringSensorBitmaskSystemFirmwareProgress(Enum):
    """IPMI Monitoring Sensor Bitmask System Firmware Progress"""
    SYSTEM_FIRMWARE_ERROR = 0x0001
    SYSTEM_FIRMWARE_HANG = 0x0002
    SYSTEM_FIRMWARE_PROGRESS = 0x0004

class IpmiMonitoringSensorBitmaskEventLoggingDisabled(Enum):
    """IPMI Monitoring Sensor Bitmask Event Logging Disabled"""
    CORRECTABLE_MEMORY_ERROR_LOGGING_DISABLED = 0x0001
    EVENT_TYPE_LOGGING_DISABLED = 0x0002
    LOG_AREA_RESET_CLEARED = 0x0004
    ALL_EVENT_LOGGING_DISABLED = 0x0008
    SEL_FULL = 0x0010
    SEL_ALMOST_FULL = 0x0020
    CORRECTABLE_MACHINE_CHECK_ERROR_LOGGING_DISABLED = 0x0040

class IpmiMonitoringSensorBitmaskWatchdog1(Enum):
    """IPMI Monitoring Sensor Bitmask Watchdog1"""
    BIOS_WATCHDOG_RESET = 0x0001
    OS_WATCHDOG_RESET = 0x0002
    OS_WATCHDOG_SHUT_DOWN = 0x0004
    OS_WATCHDOG_POWER_DOWN = 0x0008
    OS_WATCHDOG_POWER_CYCLE = 0x0010
    OS_WATCHDOG_NMI_DIAGNOSTIC_INTERRUPT = 0x0020
    OS_WATCHDOG_EXPIRED_STATUS_ONLY = 0x0040
    OS_WATCHDOG_PRE_TIMEOUT_INTERRUPT_NON_NMI = 0x0080

class IpmiMonitoringSensorBitmaskSystemEvent(Enum):
    """IPMI Monitoring Sensor Bitmask System Event"""
    SYSTEM_RECONFIGURED = 0x0001
    OEM_SYSTEM_BOOT_EVENT = 0x0002
    UNDETERMINED_SYSTEM_HARDWARE_FAILURE = 0x0004
    ENTRY_ADDED_TO_AUXILIARY_LOG = 0x0008
    PEF_ACTION = 0x0010
    TIMESTAMP_CLOCK_SYNC = 0x0020

class IpmiMonitoringSensorBitmaskCriticalInterrupt(Enum):
    """IPMI Monitoring Sensor Bitmask Critical Interrupt"""
    FRONT_PANEL_NMI_DIAGNOSTIC_INTERRUPT = 0x0001
    BUS_TIMEOUT = 0x0002
    IO_CHANNEL_CHECK_NMI = 0x0004
    SOFTWARE_NMI = 0x0008
    PCI_PERR = 0x0010
    PCI_SERR = 0x0020
    EISA_FAIL_SAFE_TIMEOUT = 0x0040
    BUS_CORRECTABLE_ERROR = 0x0080
    BUS_UNCORRECTABLE_ERROR = 0x0100
    FATAL_NMI = 0x0200
    BUS_FATAL_ERROR = 0x0400
    BUS_DEGRADED = 0x0800

class IpmiMonitoringSensorBitmaskButtonSwitch(Enum):
    """IPMI Monitoring Sensor Bitmask Button Switch"""
    POWER_BUTTON_PRESSED = 0x0001
    SLEEP_BUTTON_PRESSED = 0x0002
    RESET_BUTTON_PRESSED = 0x0004
    FRU_LATCH_OPEN = 0x0008
    FRU_SERVICE_REQUEST_BUTTON = 0x0010

class IpmiMonitoringSensorBitmaskChipSet(Enum):
    """IPMI Monitoring Sensor Bitmask Chip Set"""
    SOFT_POWER_CONTROL_FAILURE = 0x0001
    THERMAL_TRIP = 0x0002

class IpmiMonitoringSensorBitmaskCableInterconnect(Enum):
    """IPMI Monitoring Sensor Bitmask Cable Interconnect"""
    IS_CONNECTED = 0x0001
    CONFIGURATION_ERROR = 0x0002

class IpmiMonitoringSensorBitmaskSystemBootInitiated(Enum):
    """IPMI Monitoring Sensor Bitmask System Boot Initiated"""
    INITIATED_BY_POWER_UP = 0x0001
    INITIATED_BY_HARD_RESET = 0x0002
    INITIATED_BY_WARM_RESET = 0x0004
    USER_REQUESTED_PXE_BOOT = 0x0008
    AUTOMATIC_BOOT_TO_DIAGNOSTIC = 0x0010
    OS_RUN_TIME_SOFTWARE_INITIATED_HARD_RESET = 0x0020
    OS_RUN_TIME_SOFTWARE_INITIATED_WARM_RESET = 0x0040
    SYSTEM_RESTART = 0x0080

class IpmiMonitoringSensorBitmaskBootError(Enum):
    """IPMI Monitoring Sensor Bitmask Boot Error"""
    NO_BOOTABLE_MEDIA = 0x0001
    NON_BOOTABLE_DISKETTE_LEFT_IN_DRIVE = 0x0002
    PXE_SERVER_NOT_FOUND = 0x0004
    INVALID_BOOT_SECTOR = 0x0008
    TIMEOUT_WAITING_FOR_USER_SELECTION_OF_BOOT_SOURCE = 0x0010

class IpmiMonitoringSensorBitmaskOsBoot(Enum):
    """IPMI Monitoring Sensor Bitmask OS Boot"""
    A_BOOT_COMPLETED = 0x0001
    C_BOOT_COMPLETED = 0x0002
    PXE_BOOT_COMPLETED = 0x0004
    DIAGNOSTIC_BOOT_COMPLETED = 0x0008
    CD_ROM_BOOT_COMPLETED = 0x0010
    ROM_BOOT_COMPLETED = 0x0020
    BOOT_COMPLETED_BOOT_DEVICE_NOT_SPECIFIED = 0x0040
    BASE_OS_HYPERVISOR_INSTALLATION_STARTED = 0x0080
    BASE_OS_HYPERVISOR_INSTALLATION_COMPLETED = 0x0100
    BASE_OS_HYPERVISOR_INSTALLATION_ABORTED = 0x0200
    BASE_OS_HYPERVISOR_INSTALLATION_FAILED = 0x0400

class IpmiMonitoringSensorBitmaskOsCriticalStop(Enum):
    """IPMI Monitoring Sensor Bitmask OS Critical Stop"""
    CRITICAL_STOP_DURING_OS_LOAD = 0x0001
    RUN_TIME_CRITICAL_STOP = 0x0002
    OS_GRACEFUL_STOP = 0x0004
    OS_GRACEFUL_SHUTDOWN = 0x0008
    SOFT_SHUTDOWN_INITIATED_BY_PEF = 0x0010
    AGENT_NOT_RESPONDING = 0x0020

class IpmiMonitoringSensorBitmaskSlotConnector(Enum):
    """IPMI Monitoring Sensor Bitmask Slot Connector"""
    FAULT_STATUS_ASSERTED = 0x0001
    IDENTIFY_STATUS_ASSERTED = 0x0002
    SLOT_CONNECTOR_DEVICE_INSTALLED_ATTACHED = 0x0004
    SLOT_CONNECTOR_READY_FOR_DEVICE_INSTALLATION = 0x0008
    SLOT_CONNECTOR_READY_FOR_DEVICE_REMOVAL = 0x0010
    SLOT_POWER_IS_OFF = 0x0020
    SLOT_CONNECTOR_DEVICE_REMOVAL_REQUEST = 0x0040
    INTERLOCK_ASSERTED = 0x0080
    SLOT_IS_DISABLED = 0x0100
    SLOT_HOLDS_SPARE_DEVICE = 0x0200

class IpmiMonitoringSensorBitmaskSystemAcpiPowerState(Enum):
    """IPMI Monitoring Sensor Bitmask System ACPI Power State"""
    S0_G0 = 0x0001
    S1 = 0x0002
    S2 = 0x0004
    S3 = 0x0008
    S4 = 0x0010
    S5_G2 = 0x0020
    S4_S5_SOFT_OFF = 0x0040
    G3_MECHANICAL_OFF = 0x0080
    SLEEPING_IN_AN_S1_S2_OR_S3_STATES = 0x0100
    G1_SLEEPING = 0x0200
    S5_ENTERED_BY_OVERRIDE = 0x0400
    LEGACY_ON_STATE = 0x0800
    LEGACY_OFF_STATE = 0x1000
    UNSPECIFIED = 0x2000
    UNKNOWN = 0x4000

class IpmiMonitoringSensorBitmaskWatchdog2(Enum):
    """IPMI Monitoring Sensor Bitmask Watchdog2"""
    TIMER_EXPIRED = 0x0001
    HARD_RESET = 0x0002
    POWER_DOWN = 0x0004
    POWER_CYCLE = 0x0008
    RESERVED1 = 0x0010
    RESERVED2 = 0x0020
    RESERVED3 = 0x0040
    RESERVED4 = 0x0080
    TIMER_INTERRUPT = 0x0100

class IpmiMonitoringSensorBitmaskPlatformAlert(Enum):
    """IPMI Monitoring Sensor Bitmask Platform Alert"""
    PLATFORM_GENERATED_PAGE = 0x0001
    PLATFORM_GENERATED_LAN_ALERT = 0x0002
    PLATFORM_EVENT_TRAP_GENERATED = 0x0004
    PLATFORM_GENERATED_SNMP_TRAP = 0x0008

class IpmiMonitoringSensorBitmaskEntityPresence(Enum):
    """IPMI Monitoring Sensor Bitmask Entity Presence"""
    ENTITY_PRESENT = 0x0001
    ENTITY_ABSENT = 0x0002
    ENTITY_DISABLED = 0x0004

class IpmiMonitoringSensorBitmaskLan(Enum):
    """IPMI Monitoring Sensor Bitmask LAN"""
    HEARTBEAT_LOST = 0x0001
    HEARTBEAT = 0x0002

class IpmiMonitoringSensorBitmaskManagementSubsystemHealth(Enum):
    """IPMI Monitoring Sensor Bitmask Management Subsystem Health"""
    SENSOR_ACCESS_DEGRADED_OR_UNAVAILABLE = 0x0001
    CONTROLLER_ACCESS_DEGRADED_OR_UNAVAILABLE = 0x0002
    MANAGEMENT_CONTROLLER_OFF_LINE = 0x0004
    MANAGEMENT_CONTROLLER_UNAVAILABLE = 0x0008
    SENSOR_FAILURE = 0x0010
    FRU_FAILURE = 0x0020

class IpmiMonitoringSensorBitmaskBattery(Enum):
    """IPMI Monitoring Sensor Bitmask Battery"""
    BATTERY_LOW = 0x0001
    BATTERY_FAILED = 0x0002
    BATTERY_PRESENCE_DETECTED = 0x0004

class IpmiMonitoringSensorBitmaskSessionAudit(Enum):
    """IPMI Monitoring Sensor Bitmask Session Audit"""
    SESSION_ACTIVATED = 0x0001
    SESSION_DEACTIVATED = 0x0002
    INVALID_USERNAME_OR_PASSWORD = 0x0004
    INVALID_PASSWORD_DISABLE = 0x0008

class IpmiMonitoringSensorBitmaskVersionChange(Enum):
    """IPMI Monitoring Sensor Bitmask Version Change"""
    HARDWARE_CHANGE_DETECTED_WITH_ASSOCIATED_ENTITY = 0x0001
    FIRMWARE_OR_SOFTWARE_CHANGE_DETECTED_WITH_ASSOCIATED_ENTITY = 0x0002
    HARDWARE_INCOMPATABILITY_DETECTED_WITH_ASSOCIATED_ENTITY = 0x0004
    FIRMWARE_OR_SOFTWARE_INCOMPATABILITY_DETECTED_WITH_ASSOCIATED_ENTITY = 0x0008
    ENTITY_IS_OF_AN_INVALID_OR_UNSUPPORTED_HARDWARE_VERSION = 0x0010
    ENTITY_CONTAINS_AN_INVALID_OR_UNSUPPORTED_FIRMWARE_OR_SOFTWARE_VERSION = 0x0020
    HARDWARE_CHANGE_DETECTED_WITH_ASSOCIATED_ENTITY_WAS_SUCCESSFUL = 0x0040
    SOFTWARE_OR_FW_CHANGE_DETECTED_WITH_ASSOCIATED_ENTITY_WAS_SUCCESSFUL = 0x0080

class IpmiMonitoringSensorBitmaskFruState(Enum):
    """IPMI Monitoring Sensor Bitmask FRU State"""
    FRU_NOT_INSTALLED = 0x0001
    FRU_INACTIVE = 0x0002
    FRU_ACTIVATION_REQUESTED = 0x0004
    FRU_ACTIVATION_IN_PROGRESS = 0x0008
    FRU_ACTIVE = 0x0010
    FRU_DEACTIVATION_REQUESTED = 0x0020
    FRU_DEACTIVATION_IN_PROGRESS = 0x0040
    FRU_COMMUNICATION_LOST = 0x0080
